import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UserContext from "./[context]/userContext";
import CaptainContext from "./[context]/captainContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-b from-black to-[#0f1010] text-white`}
      >
        <UserContext>
          <CaptainContext>{children}</CaptainContext>
        </UserContext>
      </body>
    </html>
  );
}
